First attempt at dual macOS/linux builds in Travis

diff --git a/.ci/test b/.ci/test
--- a/.ci/test
+++ b/.ci/test
@@ -1,13 +1,26 @@
 #!/usr/bin/env bash
 
-# This will set up our environment to use the freshly-installed
-# QT 5.9 PPA packages
-source /opt/qt59/bin/qt59-env.sh
-
 set -e
 set -x
 
-qmake -v
-qmake "CONFIG+=test" "QMAKE_CXX=g++-6" "QMAKE_LINK=g++-6" -spec linux-g++  amanuensis.pro
-make
-LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/core" core-test/core-test
+if [[ $TRAVIS_OS_NAME == "linux" ]]; then
+  # This will set up our environment to use the freshly-installed
+  # QT 5.9 PPA packages
+  source /opt/qt59/bin/qt59-env.sh
+
+  qmake -v
+  qmake "CONFIG+=test" "QMAKE_CXX=g++-6" "QMAKE_LINK=g++-6" -spec linux-g++  amanuensis.pro
+  make
+  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/core" core-test/core-test
+elif [[ $TRAVIS_OS_NAME == "osx" ]]; then
+  qmake -v
+  qmake "CONFIG+=test" -spec macx-xcode amanuensis.pro
+  make
+
+  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/core" core-test/core-test && \
+  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/trusty" trusty-test/trusty-test
+
+else
+  echo "Unrecognized OS name $TRAVIS_OS_NAME; cannot continue."
+  exit 1
+fi
